// <auto-generated />
using System;
using Ferpuser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ferpuser.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210914083636_origen")]
    partial class origen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ferpuser.Models.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Authorization")
                        .HasColumnType("bit");

                    b.Property<Guid?>("BillingLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("51e91cdd-bfbd-4081-8a60-eaee0a9bea39"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Exported")
                        .HasColumnType("bit");

                    b.Property<string>("FPag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Hotel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Imported")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Notified")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<bool>("OnlyBilling")
                        .HasColumnType("bit");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("70800");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegistrantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Serie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("A ");

                    b.Property<bool>("ShowCostCenterInfoOnInvoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Units")
                        .HasColumnType("float");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VATId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BillingLocationId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanionId");

                    b.HasIndex("CongressId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RegistrantId");

                    b.HasIndex("RegistrationId")
                        .IsUnique()
                        .HasFilter("[RegistrationId] IS NOT NULL");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("Ferpuser.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AccessAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("AccessBudgetControl")
                        .HasColumnType("bit");

                    b.Property<bool>("AccessCollaborations")
                        .HasColumnType("bit");

                    b.Property<bool>("AccessCompras")
                        .HasColumnType("bit");

                    b.Property<bool>("AccessCongress")
                        .HasColumnType("bit");

                    b.Property<bool>("AccessInvoices")
                        .HasColumnType("bit");

                    b.Property<bool>("AccessMaintenance")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CongressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncomingMailPort")
                        .HasColumnType("int");

                    b.Property<string>("IncomingMailServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutgoingMailPort")
                        .HasColumnType("int");

                    b.Property<string>("OutgoingMailServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SendCopyTo")
                        .HasColumnType("bit");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureAfter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureBefore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendedor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CongressId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Ferpuser.Models.CentroCoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NivelAnalitico1")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("NivelAnalitico2")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<int>("TipoCentroCosteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoCentroCosteId");

                    b.ToTable("CentrosCoste");
                });

            modelBuilder.Entity("Ferpuser.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SageCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Ferpuser.Models.ClientLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SageClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SageLine")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientLocations");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraAlbaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoAlbaran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoOperario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompraFacturaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAlbaran")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GeneradoAutomaticamente")
                        .HasColumnType("bit");

                    b.Property<string>("NombreEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreOperario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompraFacturaId");

                    b.ToTable("CompraAlbaranes");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraAlbaranLinea", b =>
                {
                    b.Property<int>("IdAlbaranLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbaranId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoArticulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompraPedidoLineaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArticulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesAlbaranLinea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAlbaranLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Unidades")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdAlbaranLinea");

                    b.HasIndex("AlbaranId");

                    b.HasIndex("CompraPedidoLineaId");

                    b.ToTable("CompraAlbaranLineas");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoOperario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoSage")
                        .HasColumnType("int");

                    b.Property<int>("EstadoFactura")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FicheroNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FicheroUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreOperario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)")
                        .HasMaxLength(24);

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Retencion_Porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TieneRetencion")
                        .HasColumnType("bit");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CompraFacturas");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraFacturaLinea", b =>
                {
                    b.Property<int>("IdFacturaLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BaseImponiblePrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseImponibleTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoArticulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoTipoIVA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompraAlbaranLineaId")
                        .HasColumnType("int");

                    b.Property<int>("CompraFacturaId")
                        .HasColumnType("int");

                    b.Property<int?>("CompraPedidoLineaId")
                        .HasColumnType("int");

                    b.Property<int?>("IVA_Porcentaje")
                        .HasColumnType("int");

                    b.Property<string>("NombreArticulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesFacturaLinea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("Unidades")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFacturaLinea");

                    b.HasIndex("CompraAlbaranLineaId");

                    b.HasIndex("CompraFacturaId");

                    b.HasIndex("CompraPedidoLineaId");

                    b.ToTable("CompraFacturaLineas");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoOperario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoPedido")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreOperario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CompraPedidos");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraPedidoLinea", b =>
                {
                    b.Property<int>("IdPedidoLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodigoArticulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArticulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesPedidoLinea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPedidoLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Unidades")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnidadesPendientes")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPedidoLinea");

                    b.HasIndex("PedidoId");

                    b.ToTable("CompraPedidoLineas");
                });

            modelBuilder.Entity("Ferpuser.Models.Congress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attendants")
                        .HasColumnType("int");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Catering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateCreditor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CertificateCredits")
                        .HasColumnType("float");

                    b.Property<string>("CertificateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CertificateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("CommunicationsAndSocialMedia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunicationsAndType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorporatePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Database")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabasePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabasePrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatabaseUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Ended")
                        .HasColumnType("bit");

                    b.Property<string>("Financing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headquarters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HideRegistrations")
                        .HasColumnType("bit");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncomingMailPort")
                        .HasColumnType("int");

                    b.Property<string>("IncomingMailServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Infrastructures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InscriptionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InternalCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("InvoiceDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCongress")
                        .HasColumnType("bit");

                    b.Property<string>("LogoBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Organizer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutgoingMailPort")
                        .HasColumnType("int");

                    b.Property<string>("OutgoingMailServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("President")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SageAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificSecretariat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureAfter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureBefore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeakersHotel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TailBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalSecretariat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Travels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebDomain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Workplace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceDataId");

                    b.ToTable("Congresses");
                });

            modelBuilder.Entity("Ferpuser.Models.CongressEmailAccounts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncomingMailPort")
                        .HasColumnType("int");

                    b.Property<string>("IncomingMailServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("OutgoingMailPort")
                        .HasColumnType("int");

                    b.Property<string>("OutgoingMailServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureAfter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureBefore")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CongressId", "AccountId")
                        .IsUnique();

                    b.ToTable("CongressEmailAccounts");
                });

            modelBuilder.Entity("Ferpuser.Models.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51e91cdd-bfbd-4081-8a60-eaee0a9bea39"),
                            Created = new DateTime(2021, 9, 14, 10, 36, 36, 45, DateTimeKind.Local).AddTicks(9556),
                            Modified = new DateTime(2021, 9, 14, 10, 36, 36, 45, DateTimeKind.Local).AddTicks(9958),
                            Name = "Factura"
                        },
                        new
                        {
                            Id = new Guid("043d73bf-1516-4672-affe-4f0836048f40"),
                            Created = new DateTime(2021, 9, 14, 10, 36, 36, 46, DateTimeKind.Local).AddTicks(390),
                            Modified = new DateTime(2021, 9, 14, 10, 36, 36, 46, DateTimeKind.Local).AddTicks(400),
                            Name = "Factura proforma"
                        },
                        new
                        {
                            Id = new Guid("fd4d4c0d-53cb-4844-a520-cba0dac861c4"),
                            Created = new DateTime(2021, 9, 14, 10, 36, 36, 46, DateTimeKind.Local).AddTicks(423),
                            Modified = new DateTime(2021, 9, 14, 10, 36, 36, 46, DateTimeKind.Local).AddTicks(427),
                            Name = "Presupuesto"
                        });
                });

            modelBuilder.Entity("Ferpuser.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FicheroNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FicheroUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("Ferpuser.Models.Estructura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CentroCosteId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeReparto")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCosteId");

                    b.ToTable("Estructura");
                });

            modelBuilder.Entity("Ferpuser.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Authorization")
                        .HasColumnType("bit");

                    b.Property<Guid?>("BillingLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("51e91cdd-bfbd-4081-8a60-eaee0a9bea39"));

                    b.Property<bool>("Exported")
                        .HasColumnType("bit");

                    b.Property<string>("FPag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Imported")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Notified")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<bool>("OnlyBilling")
                        .HasColumnType("bit");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("bit");

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowCostCenterInfoOnInvoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("Units")
                        .HasColumnType("float");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VATId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BillingLocationId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CongressId");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Ferpuser.Models.GrabacionE9", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CentroCosteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<string>("EntradaSalida")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCosteId");

                    b.HasIndex("DestinoId");

                    b.ToTable("GrabacionE9");
                });

            modelBuilder.Entity("Ferpuser.Models.InvoiceData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SageAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TailBase64")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvoiceData");
                });

            modelBuilder.Entity("Ferpuser.Models.Origen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInforme")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gastos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ingresos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("NivelAnalitico1")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("NivelAnalitico2")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<int>("TipoCentroCosteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoCentroCosteId");

                    b.ToTable("Origen");
                });

            modelBuilder.Entity("Ferpuser.Models.PartePersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CentroCosteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonalId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoParte")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<decimal>("Unidades")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCosteId");

                    b.HasIndex("PersonalId");

                    b.HasIndex("PersonalId1");

                    b.ToTable("PartePersonal");
                });

            modelBuilder.Entity("Ferpuser.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CT")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("CentroCosteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CosteEstandar")
                        .HasColumnType("decimal(13,2)");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaApto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaRevisionMedica")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaValidezNIF")
                        .HasColumnType("datetime2");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObraId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioHora")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RevisionMedica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAP")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<int>("TipoTarifaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Venta")
                        .HasColumnType("decimal(13,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCosteId");

                    b.HasIndex("ObraId");

                    b.HasIndex("TipoTarifaId");

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("Ferpuser.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Units")
                        .HasColumnType("float");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VATId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ferpuser.Models.Registrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionalCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surnames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Workplace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.HasIndex("TreatmentId");

                    b.ToTable("Registrant");
                });

            modelBuilder.Entity("Ferpuser.Models.RegistrantLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegistrantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistrantLocations");
                });

            modelBuilder.Entity("Ferpuser.Models.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccommodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Authorization")
                        .HasColumnType("bit");

                    b.Property<Guid?>("BillingLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("51e91cdd-bfbd-4081-8a60-eaee0a9bea39"));

                    b.Property<bool>("Exported")
                        .HasColumnType("bit");

                    b.Property<string>("FPag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Imported")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Notified")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<bool>("OnlyBilling")
                        .HasColumnType("bit");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("70100");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegistrantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegistrationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("bit");

                    b.Property<string>("Serie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("I ");

                    b.Property<bool>("ShowCostCenterInfoOnInvoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("Units")
                        .HasColumnType("float");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VATId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BillingLocationId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CongressId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RegistrantId");

                    b.HasIndex("RegistrationTypeId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Ferpuser.Models.RegistrationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationTypes");
                });

            modelBuilder.Entity("Ferpuser.Models.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupants")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("Ferpuser.Models.TipoCentroCoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<decimal>("PorcentajeDistribucion")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.ToTable("TiposCentroCoste");
                });

            modelBuilder.Entity("Ferpuser.Models.TipoTarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("TiposTarifa");
                });

            modelBuilder.Entity("Ferpuser.Models.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Ferpuser.Models.Accommodation", b =>
                {
                    b.HasOne("Ferpuser.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Ferpuser.Models.ClientLocation", "BillingLocation")
                        .WithMany()
                        .HasForeignKey("BillingLocationId");

                    b.HasOne("Ferpuser.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("Ferpuser.Models.Registrant", "Companion")
                        .WithMany()
                        .HasForeignKey("CompanionId");

                    b.HasOne("Ferpuser.Models.Congress", "Congress")
                        .WithMany("Accommodations")
                        .HasForeignKey("CongressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.Registrant", "Registrant")
                        .WithMany()
                        .HasForeignKey("RegistrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.Registration", "Registration")
                        .WithOne("Accommodation")
                        .HasForeignKey("Ferpuser.Models.Accommodation", "RegistrationId");

                    b.HasOne("Ferpuser.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.Account", b =>
                {
                    b.HasOne("Ferpuser.Models.Congress", "Congress")
                        .WithMany()
                        .HasForeignKey("CongressId");
                });

            modelBuilder.Entity("Ferpuser.Models.CentroCoste", b =>
                {
                    b.HasOne("Ferpuser.Models.TipoCentroCoste", "TipoCentroCoste")
                        .WithMany()
                        .HasForeignKey("TipoCentroCosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.ClientLocation", b =>
                {
                    b.HasOne("Ferpuser.Models.Client", "Client")
                        .WithMany("Locations")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraAlbaran", b =>
                {
                    b.HasOne("Ferpuser.Models.CompraFactura", "CompraFactura")
                        .WithMany("CompraAlbaranes")
                        .HasForeignKey("CompraFacturaId");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraAlbaranLinea", b =>
                {
                    b.HasOne("Ferpuser.Models.CompraAlbaran", "Albaran")
                        .WithMany("AlbaranLineas")
                        .HasForeignKey("AlbaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.CompraPedidoLinea", "CompraPedidoLinea")
                        .WithMany("AlbaranLineas")
                        .HasForeignKey("CompraPedidoLineaId");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraFacturaLinea", b =>
                {
                    b.HasOne("Ferpuser.Models.CompraAlbaranLinea", "CompraAlbaranLinea")
                        .WithMany()
                        .HasForeignKey("CompraAlbaranLineaId");

                    b.HasOne("Ferpuser.Models.CompraFactura", "CompraFactura")
                        .WithMany("FacturaLineas")
                        .HasForeignKey("CompraFacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.CompraPedidoLinea", "CompraPedidoLinea")
                        .WithMany()
                        .HasForeignKey("CompraPedidoLineaId");
                });

            modelBuilder.Entity("Ferpuser.Models.CompraPedidoLinea", b =>
                {
                    b.HasOne("Ferpuser.Models.CompraPedido", "Pedido")
                        .WithMany("PedidoLineas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.Congress", b =>
                {
                    b.HasOne("Ferpuser.Models.InvoiceData", "InvoiceData")
                        .WithMany()
                        .HasForeignKey("InvoiceDataId");
                });

            modelBuilder.Entity("Ferpuser.Models.CongressEmailAccounts", b =>
                {
                    b.HasOne("Ferpuser.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.Congress", "Congress")
                        .WithMany("CongressEmailAccounts")
                        .HasForeignKey("CongressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.Documento", b =>
                {
                    b.HasOne("Ferpuser.Models.Personal", "Personal")
                        .WithMany("Documentos")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.Estructura", b =>
                {
                    b.HasOne("Ferpuser.Models.CentroCoste", "CentroCoste")
                        .WithMany()
                        .HasForeignKey("CentroCosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.Expense", b =>
                {
                    b.HasOne("Ferpuser.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Ferpuser.Models.ClientLocation", "BillingLocation")
                        .WithMany()
                        .HasForeignKey("BillingLocationId");

                    b.HasOne("Ferpuser.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("Ferpuser.Models.Congress", "Congress")
                        .WithMany("Expenses")
                        .HasForeignKey("CongressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.GrabacionE9", b =>
                {
                    b.HasOne("Ferpuser.Models.CentroCoste", "CentroCoste")
                        .WithMany()
                        .HasForeignKey("CentroCosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.CentroCoste", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.Origen", b =>
                {
                    b.HasOne("Ferpuser.Models.TipoCentroCoste", "TipoCentroCoste")
                        .WithMany()
                        .HasForeignKey("TipoCentroCosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.PartePersonal", b =>
                {
                    b.HasOne("Ferpuser.Models.CentroCoste", "CentroCoste")
                        .WithMany()
                        .HasForeignKey("CentroCosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.Personal", null)
                        .WithMany("Partes")
                        .HasForeignKey("PersonalId1");
                });

            modelBuilder.Entity("Ferpuser.Models.Personal", b =>
                {
                    b.HasOne("Ferpuser.Models.CentroCoste", "CentroCoste")
                        .WithMany()
                        .HasForeignKey("CentroCosteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.CentroCoste", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId");

                    b.HasOne("Ferpuser.Models.TipoTarifa", "TipoTarifa")
                        .WithMany()
                        .HasForeignKey("TipoTarifaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.Product", b =>
                {
                    b.HasOne("Ferpuser.Models.Expense", "Expense")
                        .WithMany("Products")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.Registrant", b =>
                {
                    b.HasOne("Ferpuser.Models.RegistrantLocation", "Location")
                        .WithOne("Registrant")
                        .HasForeignKey("Ferpuser.Models.Registrant", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ferpuser.Models.Registration", b =>
                {
                    b.HasOne("Ferpuser.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Ferpuser.Models.ClientLocation", "BillingLocation")
                        .WithMany()
                        .HasForeignKey("BillingLocationId");

                    b.HasOne("Ferpuser.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("Ferpuser.Models.Congress", "Congress")
                        .WithMany("Registrations")
                        .HasForeignKey("CongressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.Registrant", "Registrant")
                        .WithMany()
                        .HasForeignKey("RegistrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ferpuser.Models.RegistrationType", "RegistrationType")
                        .WithMany()
                        .HasForeignKey("RegistrationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
